language: python
python:
  - "3.3"
  - "3.2"
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - if [[ $TRAVIS_PYTHON_VERSION < '3.3' ]]; then pip install --use-mirrors mock; fi
  - pip install --use-mirrors mock nose
  - python setup.py install
# command to run tests, e.g. python setup.py test
script:
  # Must run the tests in build/src so python3 doesn't get confused and run
  # the python2 code from the current directory instead of the installed
  # 2to3 version in build/src.
  - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '3' ]]; then 2to3 -w -n --no-diffs convutils; fi
  - nosetests
